#!/bin/bash

awk 'NR>2{print $1," core ",$2,$3,$4,"  0.0 1.0 0.0"}' coord.xyz > coord

cat head coord tail > tor.gin
gulp < tor.gin > tor.gout

grep 'Total lattice' tor.gout |grep eV | awk '{print $(NF-1)}' > tor.dat

awk '/Final/{n=NR+6} NR==n {on=1}/-----------/{on=0} on{print $4,$5,$6}' tor.gout >> tor.dat
