#!/bin/bash

awk 'NR>2{print "C 6.0 ",$2,$3,$4}' coord.xyz > coord

cat head coord tail > tor.inp
\rm PUNCH
pgamess-712-class-p4 -i tor.inp -o tor.out

grep FINAL tor.out | awk '{print $4}' > tor.dat

awk '/GRADIENT OF THE ENERGY/{n=NR+4} NR==n {on=1}/MAXIMUM GRADIENT/{on=0} on{print $3,$4,$5}'  tor.out >> tor.dat


